kill @e[type=spider,r=80]
kill @e[type=skeleton,r=80]
kill @e[type=creeper,r=80]
kill @e[type=zombie_villager,r=80]
kill @e[type=goat,r=80]
kill @e[type=cow,r=80]
kill @e[type=sheep,r=80]
kill @e[type=witch,r=80]
kill @e[type=enderman,r=80]
kill @e[type=wandering_trader,r=80]
kill @e[type=zombie,name=!"§4Esbirro",r=80]

kill @e[type=item,rm=53,r=140]